# Generated by Django 3.2.9 on 2021-11-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonBotSites', '0002_alter_prodotto_descrizione'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodotto',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='ID_Prodotto',
            new_name='ID_Product',
        ),
    ]
