# Generated by Django 3.2.9 on 2021-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonBotSites', '0003_auto_20211121_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(),
        ),
    ]
