# Generated by Django 3.2.9 on 2021-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonBotSites', '0004_alter_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ID_Product', models.ManyToManyField(to='AmazonBotSites.Product')),
            ],
        ),
    ]
