# Generated by Django 3.2.9 on 2021-11-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonBotSites', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ID_Product',
            new_name='product',
        ),
    ]
